### ISSUE TITLE
CoreContainer is either not initialized or shutting down

### ISSUE THREAD

**Issue by micheladennis** [freedev/solrcloud-zookeeper-kubernetes#7]
Unzip Project
run ./start-aws-zookeeper-ensemble.sh
then
run ./start-aws-solr-cluster.sh

View solr service URL / IP in browser

 get error:
javax.servlet.ServletException: javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.

**Comment by freedev** [comment]
Hi @micheladennis are still you still struggling with this? It's not clear exactly what was gone wrong, very likely you had a problem with the persistent storage initialisation.

**Comment by sgangapa** [comment]
Dear Freedev Team ,

I have followed your statefulset deployments for solr cluster with zookeeper on kubernetes cluster. While I'm trying to install solr cloud cluster on my local kubernetes cluster( 3 nodes) and facing following issues. Basically, solr is unable to connect zookeeper services.

Could you please help me on wat has been wrong in deployments?

Solr logs:
=======
Caused by: org.apache.solr.common.SolrException: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper zk-0.zkensemble:2181,zk-1.zkensemble:2181,zk-2.zkensemble:2181 within 30000 ms

Zookeeper logs:
==========
/bin/sh: hostname: command not found
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg

**Comment by suresh-offcl** [comment]
Is this repository active?

**Comment by freedev** [comment]
@suresh-offcl thanks for contributing. Could you please write down which steps lead you to this result?

**Comment by suresh-offcl** [comment]
The issue seems to be coming while executing docker-entrypoint.sh file in zookeeper docker image where hostname is not getting resolved.. 

​if​ [ ​"​$ZOO_SERVERS​"​ ​!=​ ​"​"​ ]
​then​
  ​echo​ ​$ZOO_SERVERS​ ​|​ sed ​"​s/​$(​**hostname**​)​.zkensemble/0.0.0.0/g​"​ ​>​ /conf/zooservers.txt
  cat /conf/zooservers.txt
  ​export​ ZOO_SERVERS=​"​$(​ cat /conf/zooservers.txt ​)​"​
​fi​

The solr and zookeeper log traces provided in earlier comment.

**Comment by suresh-offcl** [comment]
Also,  I'm not finding stable solr and zookeeper helm charts for production setup..

**Comment by suresh-offcl** [comment]
**kubectl logs -f zk-0**

/bin/sh: hostname: command not found
/docker-entrypoint.sh: line 7: hostname: command not found
server.1=zk-00.0.0.0:2888:3888 server.2=zk-10.0.0.0:2888:3888 server.3=zk-20.0.0.0:2888:3888
/docker-entrypoint.sh: line 7: hostname: command not found
server.1=zk-00.0.0.0:2888:3888 server.2=zk-10.0.0.0:2888:3888 server.3=zk-20.0.0.0:2888:3888
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg

**Comment by freedev** [comment]
@suresh-offcl this logs is completely unrelated with the source code. When opening a ticket, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. In general, this is referred to by community members as creating a minimal, reproducible example (reprex), a minimal, complete and verifiable example (mcve), or a minimal, workable example (mwe).

**Comment by freedev** [comment]
For a better result your issue should be…

…Minimal – Use as little code as possible that still produces the same problem
…Complete – Provide all parts someone else needs to reproduce your problem in the question itself
…Reproducible – Test the code you're about to provide to make sure it reproduces the problem
The rest of this help article provides guidance on these aspects of writing a minimal, reproducible example.

Hope this helps.

**Comment by gs-offcl** [comment]
Logs are straightforward...anyways,  I will open a new ticket and provide detailed steps...

**Comment by gs-offcl** [comment]
Have opened up a new ticket and detailed out steps...please check.
